[package]
name = "snazzy"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
description = "Example project using prost-build"
edition = "2018"

[dependencies]
prost = "0.11.9"
prost-types = "0.11.9"
bytes = "1.4.0"

[build-dependencies]
prost-build = "0.11.9"
